name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clj
      run: |
        sudo apt-get install -y rlwrap
        curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
        chmod +x linux-install-1.10.1.763.sh
        sudo ./linux-install-1.10.1.763.sh
    - name: Run tests
      run: clj -M:test
